### PR TITLE
[Proposal] Javascript restructure

### PR DESCRIPTION
**Pull request by sebastiandedeyne**
This PR changes the javascript file structure from this:

```
js/
  back/
    modules/
      <...blender modules>
    redactor/
    app.js
    head.js
  front/
    app.js
    head.js
```

To this:

```
js/
  blender/
    <...blender modules>
  redactor/
  back.app.js
  back.head.js
  front.app.js
  front.head.js
```

It also adds absolute imports, e.g. `import components/calendar;` instead of `import ../components/calendar;`

Todo: prefix imports with something like `app` so they can't clash with real packages.
## Reasoning
- Relative import paths in larger applications are hard to refactor. If we were to enable absolute paths with the current structure, we'd have to prefix every import with `front` or `back`, which isn't nice either
- Javascript for the backoffice is generally relatively simple. In the cases that it isn't simple, it mostly means it has a shared part of the code base with the front. This way it's easier to share code without having to introduce an awkward `shared` folder.
- All entry scripts are at the top level now, which gives a nice overview of the application
## Upsides
- All of the above
## Downsides
- Folder structure is different from views and css

### CODE REVIEW

**Comment by freekmurze** [comment]
More pros than cons, so 👍  from me.

**Comment by willemvb** [comment]
Random thoughts:
- The terms 'back' and 'blender' are both used in the application. Could be cleaner if we used the 'blender' name across the entire app? (`blender.head.js`, `views/blender` etc.)
- Will there be an optional `/js/front` folder as well for front modules?

**Comment by sebastiandedeyne** [comment]
> The terms 'back' and 'blender' are both used in the application

I wouldn't mind this

> Will there be an optional /js/front folder as well for front modules?

Front code structure would have carte blanche. I'd use a `front` folder for smaller things, but if we're pretty much building a SPA, like a large form wizard, I'd let it exist in it's own feature folder.

```
js/
  blender/
  redactor/
  wizard/
  widget/
  <...entry scripts>
```

**Comment by willemvb** [comment]
Front code structure carte blanche sounds fine!

Naming of the `/blender` folder still bothers me a little, might be subjective. There seems to be no other `/blender` folder in the application in eg. Controllers, Services/Auth, Views, Sass,...

Come to think of it: shouldn't `editor.js` and `chart.js` be made a part of `blender.js` instead so we can skip this extra folder all together?

**Comment by sebastiandedeyne** [comment]
Editor used to be in `blender.js`, forgot why we moved it :/

Sounds good to get everything in there. Would be nice to give `blender.js` some refactoring love too, I'll try to make some time for it soonish, and defer merging this until then.

Makes sense that we shouldn't even need a `back` or `blender` folder for most projects.

Further thoughts: would be nice to have the same with `sass/back`, so we can easily keep Blender styles up to date instead of manually having to update them on new features (of course major class name changes would require a new major version)

**Comment by willemvb** [comment]
How about a `blender.css` package?

**Comment by sebastiandedeyne** [comment]
👍

**Comment by sebastiandedeyne** [comment]
Holding off on this for now.

**Pull request closed without merging**
